/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:841f8295-65f5-4b4c-bcac-7dfb6d12a3ef",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_2xkfh2Exx",
    "aws_user_pools_web_client_id": "4utinfscfi21h544672k01ivc9",
    "oauth": {}
};


export default awsmobile;
